// คำค้นสำรองของเครื่องมือ (เดิมคือช่อง keys ในทะเบียน) ใช้ตอนค้นหาเท่านั้น
// ‼️ แยกออกจาก src/registry.js 26/09/2026 เพราะหน้าแรกไม่ได้ใช้จนกว่าจะมีคนพิมพ์ค้น
//    app.js ดึงไฟล์นี้พร้อม src/search.js ตอนชี้หรือโฟกัสช่องค้นหา หน้าแรกเบาลงราว 3 KB (งบ JS หน้าแรกเต็ม)
//    import ไฟล์นี้ = คำค้นถูกใส่ลง t.keys ของทุกเครื่องมือทันที search.js อ่าน t.keys เหมือนเดิมทุกบรรทัด
// ‼️ เพิ่มเครื่องมือใหม่ต้องใส่คำค้นที่นี่ด้วย และห้ามใส่ keys ใน registry.js (tests/accepts.test.mjs ตรวจทั้งสองข้อ)
import { TOOLS } from "./registry.js";

export const KEYS = {
  "pdf-pages": "page manager หน้า ลบหน้า หมุน เรียง จัดการ จัดระเบียบ organize หลายไฟล์",
  "pdf-edit": "edit แก้ไข ข้อความ ลบข้อความ ปิดทับ วันที่ พิมพ์ทับ redact ไฮไลต์ highlight เน้นข้อความ เซ็น ลายเซ็น sign วางรูป โลโก้ ตราประทับ stamp",
  "pdf-merge": "merge combine รวม ต่อ เล่ม",
  "pdf-split": "split แยก ตัด ช่วงหน้า",
  "pdf-compress": "compress บีบอัด ลดขนาด เล็กลง",
  "pdf-sign": "sign signature เซ็น ลายเซ็น เซ็นชื่อ สัญญา ใบลา อนุมัติ",
  "pdf-protect": "protect encrypt password lock ใส่รหัส ตั้งรหัส รหัสผ่าน ล็อก ล็อค เข้ารหัส ป้องกัน ความลับ ห้ามพิมพ์ ห้ามคัดลอก",
  "pdf-compare": "compare diff เทียบ เปรียบเทียบ สองฉบับ แก้ตรงไหน ฉบับแก้ไข สัญญา ร่าง ต่างกัน",
  "pdf-crop": "crop trim ครอบตัด ตัดขอบ ขอบดำ สแกน ขอบขาว ย่อกรอบ",
  "pdf-resize": "resize paper size ขนาดกระดาษ a4 a5 letter legal เปลี่ยนขนาด ย่อขยาย แนวตั้ง แนวนอน",
  "pdf-nup": "nup booklet หลายหน้าต่อแผ่น ประหยัดกระดาษ พับครึ่ง เย็บกลาง เล่มเล็ก สูจิบัตร คู่มือ 2in1 4in1",
  "pdf-clean": "clean metadata sanitize ตรวจก่อนส่ง ล้างข้อมูล ชื่อผู้เขียน คอมเมนต์ ฟอร์ม ไฟล์แนบ สคริปต์ ข้อมูลแฝง",
  "pdf-redact": "redact censor ลบข้อมูล ปิดทับ ข้อมูลลับ เซ็นเซอร์ ปกปิด ดำ ลบชื่อ ลบเลขบัตร ลบข้อความจริง",
  "pdf-unlock": "unlock decrypt remove password ปลดรหัส ถอดรหัส เอารหัสออก ปลดล็อก ปลดล็อค เปิดไฟล์ล็อก คัดลอกไม่ได้ พิมพ์ไม่ได้",
  "pdf-watermark": "watermark ลายน้ำ ประทับ ลับ confidential ตราประทับ",
  "pdf-unstamp": "remove watermark stamp layer ลบลายน้ำ เอาลายน้ำออก ลบตรา ลบชั้น ลบโลโก้ทับ overlay",
  "pdf-page-numbers": "page number เลขหน้า เลขไทย หน้า numbering ปกสารบัญ รายงาน bates เลขรัน เลขลำดับเอกสาร หัวกระดาษ ท้ายกระดาษ header footer ประทับข้อความ คดี ตรวจสอบ",
  "pdf-remove-blank": "blank ว่าง เปล่า สแกน scan ลบหน้า สองหน้า duplex หน้าคู่",
  "pdf-ocr": "ocr สแกน อ่านข้อความ ตัวอักษร ตัวหนังสือ รูปภาพ ภาพถ่าย recognize",
  "pdf-extract-images": "extract images ดึงรูป เอารูปออก รูปภาพใน pdf แกะรูป โบรชัวร์ ภาพประกอบ",
  "pdf-to-powerpoint": "powerpoint pptx สไลด์ นำเสนอ ฉาย ประชุม เด็ค ppt แปลงเป็นสไลด์",
  "pdf-to-images": "image png jpg รูป ภาพ export",
  "pdf-to-longimage": "long image ภาพยาว ต่อภาพ ไลน์ line แชท ส่งรูป สกรีนช็อต pdf เป็นรูป",
  "pdf-to-text": "text txt ข้อความ ดึง copy",
  "pdf-to-word": "word docx เอกสาร แก้ไข",
  "pdf-to-excel": "excel xlsx ตาราง table sheet",
  "image-convert": "png jpg webp แปลง รูป convert ico favicon ไอคอน ไอคอนเว็บ",
  "image-resize": "resize compress ย่อ ลดขนาด บีบอัด รูป",
  "image-bg-remove": "background remove transparent โปร่งใส ลบพื้นหลัง ตัดพื้นหลัง ลายเซ็น ตราประทับ โลโก้ png ฉากหลัง",
  "images-to-pdf": "image jpg png รูป รวม pdf",
  "word-join": "merge join รวม ต่อ เอกสาร word docx เล่ม รายงาน",
  "word-replace": "find replace ค้นหา แทนที่ หลายไฟล์ batch แก้ทั้งชุด word",
  "word-clean": "clean metadata comment track changes ตรวจ ล้าง คอมเมนต์ ประวัติ ผู้เขียน ความลับ ส่งออก",
  "word-mailmerge": "mailmerge mail merge จดหมายเวียน เทมเพลต template word excel ใบรับรอง ใบเสร็จ เวียน",
  "word-to-pdf": "word docx pdf แปลง",
  "text-to-pdf": "text txt ข้อความ โน้ต note บันทึก พิมพ์ เป็น pdf แปลง ตัวอักษร พิมพ์ข้อความ",
  "powerpoint-to-word": "powerpoint ppt pptx สไลด์ word docx โน้ต presentation แปลง",
  "powerpoint-to-pdf": "powerpoint ppt pptx สไลด์ pdf presentation แปลง แจก",
  "excel-match-sum": "solver subset sum กระทบยอด reconcile หายอด รวมกันได้ จับคู่ยอด เงินโอน ใบแจ้งหนี้ ผลต่าง หาตัวที่หาย combination excel solver what combination adds up",
  "excel-csv": "csv excel xlsx แปลง data ข้อมูล",
  "excel-split": "split แยก แบ่ง group แผนก สาขา จังหวัด ตามคอลัมน์ excel",
  "excel-merge": "merge รวม ต่อ combine consolidate หลายไฟล์ สาขา excel",
  "excel-to-pdf": "excel xlsx sheet ตาราง pdf",
  "excel-to-pq": "power query m code #table pq โค้ด สูตร excel ชนิดข้อมูล type int64 currency pdf word รูป ocr",
  "thai-encoding": "encoding tis-620 windows-874 utf-8 เพี้ยน ต่างดาว อ่านไม่ออก มั่ว csv ภาษาไทย ยึกยือ",
  "thai-date": "พ.ศ. ค.ศ. buddhist christian ปี วันที่ 543 แปลงปี date excel",
  "thai-id": "บัตรประชาชน เลขบัตร ผู้เสียภาษี tax id 13 หลัก ตรวจสอบ checksum",
  "thai-name": "ชื่อ นามสกุล คำนำหน้า นาย นาง นางสาว แยกชื่อ split name title prefix hr รายชื่อ",
  "thai-address": "ที่อยู่ จังหวัด อำเภอ ตำบล เขต แขวง รหัสไปรษณีย์ address province district subdistrict postcode แยกที่อยู่",
  "thai-number": "บาทถ้วน ตัวหนังสือ อ่านตัวเลข bahttext เลขไทย อารบิก ใบเสนอราคา ใบกำกับ เช็ค",
  "pbi-donut": "deneb donut vega โดนัท วงกลม power bi custom visual กราฟ pie พาย",
  "pbi-bar": "deneb bar vega แท่ง แนวนอน power bi custom visual กราฟ ranking จัดอันดับ target เป้าหมาย",
  "freebies": "แจก ฟรี ของแถม สำเร็จรูป template deneb spec m code power query ดาวน์โหลด ก๊อปไปใช้ freebies gift",
  "pbi-matrix-details": "matrix dax measure text power bi ตรึงคอลัมน์ freeze รายละเอียด transaction details concatenatex sqlbi ยุบคอลัมน์ ข้อความในตาราง",
  "pbi-theme": "theme json power bi ธีม สี แบรนด์ corporate palette dataColors textClasses คอนทราสต์ ตาบอดสี accessibility contrast",
  "pa-parse-json": "power automate flow parse json schema พาร์ส เจสัน โฟลว์ สคีมา อัตโนมัติ",
  "map-coverage": "map แผนที่ รัศมี radius วง circle พื้นที่ area coverage buffer call center คอลเซ็นเตอร์ ใกล้ที่สุด nearest ระยะทาง distance haversine icon map pro wkt polygon slicer จุดศูนย์กลาง ครอบคลุม",
  "map-relocate": "map แผนที่ ย้ายสถานี relocate relocation กระจัด พิกัด lat lon latitude longitude ระยะทาง distance haversine icon map pro wkt linestring polygon รัศมี site move จุดเดิม จุดใหม่",
  "number-bins": "bin binning จัดกลุ่ม แบ่งช่วง ช่วงตัวเลข band bucket range histogram การกระจาย อายุงาน sla ค่าเช่า ระยะทาง quantile quartile decile jenks natural breaks เลขกลม group by range sort by column เรียงมั่ว เรียงผิด",
  "pq-multisource-lookup": "power query m lookup merge fallback multisource รวมแหล่ง ค้นข้าม vlookup ไล่หา cascade",
  "pq-group-concat": "power query m group concat ยุบแถว รวมแถว ต่อข้อความ combine rows group by textjoin concatenate สรุปต่อกลุ่ม latest contract sql server t-sql string_agg for xml path",
  "pq-to-date": "power query m date text แปลงวันที่ พศ คศ buddhist era ปฏิทิน type date locale culture วันที่เพี้ยน 543 เปลี่ยนชนิดข้อมูล sql server t-sql try_convert dateadd",
  "pq-pick-date": "power query m date max min rank วันล่าสุด วันแรกสุด อันดับ sla ช่วงห่าง list max หลายคอลัมน์ เลือกวันที่ sql server t-sql cross apply row_number",
  "pq-combine": "power query m append table.combine หลาย server รวม query ยุบ staging parameter",
  "pa-html-table": "power automate flow email html table outlook อีเมล ตาราง เมล compose create html table",
};

for (const t of TOOLS) t.keys = KEYS[t.id] || "";
