/* ตัวช่วยเขียน T-SQL ให้ถูกไวยากรณ์เสมอ ใช้ร่วมกันทุกเครื่องมือหมวด Power Query
 *
 * ‼️ ทุกอย่างในไฟล์นี้พิสูจน์กับ SQL Server 2022 Developer Edition จริงแล้ว 14/09/2026
 *    (ดู References/Knowledge/PROVEN.md หัวข้อ T-SQL) ไม่ใช่ไวยากรณ์ที่จำ ๆ มาเขียน
 *
 * ‼️ สองข้อที่ทำให้ผลต่างจาก Power Query แบบเงียบ ๆ ถ้าไม่ระวัง
 *    ① STRING_AGG ข้ามค่าว่างให้เอง เหมือน List.RemoveNulls ใน M เป๊ะ
 *       ต่อหลายคอลัมน์พร้อมกันแล้วจำนวนสมาชิกจะไม่เท่ากัน ต้องห่อ COALESCE เสมอ
 *    ② ไม่ใส่ WITHIN GROUP (ORDER BY ...) แล้วลำดับไม่แน่นอน ของจริงเคยคืนกลับด้านกับ M
 */
import { tr } from "./i18n.js";

/** ชื่อคอลัมน์หรือตาราง ครอบวงเล็บเหลี่ยมเสมอ ปลอดภัยกับชื่อไทยและชื่อมีเว้นวรรค */
export function sqlId(name) {
  return `[${String(name ?? "").replace(/]/g, "]]")}]`;
}

/** ชื่อที่อาจมาเป็น schema.table เช่น dbo.Contracts ให้ครอบทีละท่อน */
export function sqlTable(name) {
  const raw = String(name ?? "").trim();
  if (!raw) return sqlId("");
  return raw.split(".").map((part) => sqlId(part.replace(/^\[|\]$/g, ""))).join(".");
}

/** ข้อความ ใช้ N'...' เสมอเพราะข้อมูลไทยต้องเป็น Unicode */
export function sqlStr(s) {
  return `N'${String(s ?? "").replace(/'/g, "''")}'`;
}

/**
 * ต่อข้อความของหลายแถวเป็นค่าเดียว
 * modern = SQL Server 2017 ขึ้นไป ใช้ STRING_AGG
 * legacy = เก่ากว่านั้น ใช้ FOR XML PATH ซึ่งต้อง STUFF ตัดตัวคั่นตัวแรกทิ้ง
 */
export function stringAgg({ expr, sep, orderBy, dialect, from, where }) {
  const sepStr = sqlStr(sep);
  if (dialect !== "legacy") {
    const within = orderBy ? ` WITHIN GROUP (ORDER BY ${orderBy})` : "";
    return `STRING_AGG(CAST(${expr} AS nvarchar(MAX)), ${sepStr})${within}`;
  }
  // ‼️ ท่าเก่าต้องมีคิวรีย่อยของตัวเอง จึงต้องรู้ FROM และเงื่อนไขจับกลุ่มด้วย
  const ord = orderBy ? ` ORDER BY ${orderBy}` : "";
  const w = where ? ` WHERE ${where}` : "";
  return `STUFF((SELECT ${sepStr} + CAST(${expr} AS nvarchar(MAX))`
    + ` FROM ${from}${w}${ord} FOR XML PATH(''), TYPE).value('.', 'nvarchar(MAX)'), 1, ${sep.length}, N'')`;
}

/** ค่าว่างต้องมีตัวแทนที่มองเห็น ไม่งั้นตำแหน่งเลื่อนแบบเดียวกับใน Power Query */
export function coalesceText(col, nullText) {
  return nullText === null ? col : `COALESCE(${col}, ${sqlStr(nullText)})`;
}

/** ตัวเลือกรุ่นของเซิร์ฟเวอร์ ใช้เป็น options ของ <select> ได้ตรง ๆ */
export const DIALECTS = () => [
  ["modern", tr("SQL Server 2017 ขึ้นไป", "SQL Server 2017 or newer")],
  ["legacy", tr("เก่ากว่า 2017", "Older than 2017")],
];

/** คำอธิบายใต้ช่องเลือกรุ่น บอกว่าต่างกันตรงไหนจริง ๆ */
export const DIALECT_HINT = (d) => d === "legacy"
  ? tr("รุ่นเก่าไม่มี STRING_AGG ต้องใช้ท่า FOR XML PATH ซึ่งยาวกว่าและอ่านยากกว่า",
       "Older versions have no STRING_AGG, so it falls back to FOR XML PATH which is longer and harder to read")
  : tr("ใช้ STRING_AGG ซึ่งมีมาตั้งแต่ SQL Server 2017",
       "Uses STRING_AGG, available since SQL Server 2017");

/** หัวคอมเมนต์ของสคริปต์ บอกที่มาให้คนเปิดไฟล์เจอทีหลังรู้ว่าได้มาจากไหน */
export function sqlHeader(what) {
  return tr(`-- ${what} (สร้างจาก FileKit)`, `-- ${what} (generated by FileKit)`);
}

/** ตัดบรรทัดยาวไม่ได้เหมือนโค้ด M จึงมีแค่ตัวช่วยย่อหน้าให้อ่านง่าย */
export function indent(lines, n = 4) {
  const pad = " ".repeat(n);
  return lines.map((l) => (l ? pad + l : l));
}
